name: Deploy to AWS Lambda

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.12'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Package Lambda
      run: |
        mkdir -p lambda-package
        cp blog_agent.py lambda-package/
        cd lambda-package
        pip install -t . requests
        zip -r ../blog_agent.zip .

    - name: Update Lambda functions
      run: |
        for func in blog-daily-workflow blog-approval-handler blog-manual-trigger; do
          aws lambda update-function-code \
            --function-name $func \
            --zip-file fileb://blog_agent.zip \
            --region us-east-1
        done

    - name: Notify on success
      if: success()
      run: echo "✅ Lambda functions updated successfully"

    - name: Notify on failure
      if: failure()
      run: echo "❌ Deployment failed"
